import type { Metadata } from "next";
import "@/style/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import PageEnterAnimation from "@/components/PageEnterAnimation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signUpForceRedirectUrl="/dashboard"
      signInForceRedirectUrl="/dashboard"
    >
      <html lang="en">
        <body className="relative">
          {children}
          <PageEnterAnimation />
        </body>
      </html>
    </ClerkProvider>
  );
}
